name: Streamlit CI/CD with Artifact Registry

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
      - name: Build Docker image
        run: gcloud builds submit --tag us-central1-docker.pkg.dev/dspl-ai-ml-coe-pocs/ner-with-rl/reinforcement-learning:latest .
      - name: Deploy to Cloud Run
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          gcloud run deploy your-service-name \
            --image us-central1-docker.pkg.dev/dspl-ai-ml-coe-pocs/ner-with-rl/reinforcement-learning:latest \
            --platform managed