steps:
  - name: python:3.12.1
    entrypoint: pip
    args: ['install', '-r', 'requirements.txt']

  - name: building
    args: ['builds', 'submit', '--tag', 'us-central1-docker.pkg.dev/dspl-ai-ml-coe-pocs/ner-with-rl/reinforcement-learning:latest', '.']

  - name: connection_1
    entrypoint: bash
    args:
      - '-c'
      - |
        gcloud auth configure-docker us-central1-docker.pkg.dev \
          --iam-account="for-ner@dspl-ai-ml-coe-pocs.iam.gserviceaccount.com"
        gcloud run deploy your-service-name \
          --image us-central1-docker.pkg.dev/dspl-ai-ml-coe-pocs/ner-with-rl/reinforcement-learning \
          --platform managed \
          --service-account="for-ner@dspl-ai-ml-coe-pocs.iam.gserviceaccount.com" \
          --allow-unauthenticated

  - name: deployment
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deploying to Cloud Run.....!"
        gcloud run deploy "reinforcement-learning" \
          --source . \
          --project="dspl-ai-ml-coe-pocs" \
          --service-account="for-ner@dspl-ai-ml-coe-pocs.iam.gserviceaccount.com" \
          --region="us-central1" \
          --platform managed \
          --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY