# steps:
#   - name: python:3.12.1
#     entrypoint: pip
#     args: ['install', '-r', 'requirements.txt']

#   - name: us-central1-docker.pkg.dev/dspl-ai-ml-coe-pocs/ner-with-rl/reinforcement-learning
#     entrypoint: 'bash'
#     args:
#       - '-c'
#       - |
#         gcloud auth configure-docker us-central1-docker.pkg.dev \
#           --image us-central1-docker.pkg.dev/dspl-ai-ml-coe-pocs/ner-with-rl/reinforcement-learning \
#           --platform managed \
#           --service-account="for-ner@dspl-ai-ml-coe-pocs.iam.gserviceaccount.com" \
#           --allow-unauthenticated

#   - name: us-central1-docker.pkg.dev/dspl-ai-ml-coe-pocs/ner-with-rl/reinforcement-learning
#     entrypoint: 'bash'
#     args:
#       - '-c'
#       - |
#         echo "Deploying to Cloud Run.....!"
#         gcloud run deploy "reinforcement-learning" \
#           --source . \
#           --project="dspl-ai-ml-coe-pocs" \
#           --service-account="for-ner@dspl-ai-ml-coe-pocs.iam.gserviceaccount.com" \
#           --region="us-central1" \
#           --platform managed \
#           --allow-unauthenticated
# options:
#   logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deploying to Cloud Run.....!"
        gcloud run deploy reinforcement-learning \
          --source . \
          --project="dspl-ai-ml-coe-pocs" \
          --service-account="for-ner@dspl-ai-ml-coe-pocs.iam.gserviceaccount.com" \
          --region="us-central1" \
          --platform managed \
          --allow-unauthenticated
options:
  logging: CLOUD_LOGGING_ONLY